#!/bin/bash NOT A REAL SHELL SCRIPT!
# This is a cut'n'paste scriptlet
# be sure to read & understand what you're cutting & pasting!
#
# these are notes for Geard, OpenStack, and OpenShift

################################################################################
## geard
#Usage: 
#  gear [flags]
#  gear [command]
#Available Commands: 
#  deploy <file> <host>...              :: Deploy a set of containers to the named hosts
#  install <image> <name>... [<env>]    :: Install a docker image as a systemd service
#  delete <name>...                     :: Delete an installed container
#  build <source> <image> <tag> [<env>] :: (Local) Build a new image on this host
#  set-env <name>... [<env>]            :: Set environment variable values on servers
#  env <name>...                        :: Retrieve environment variable values by id
#  link <name>...                       :: Set network links for the named containers
#  start <name>...                      :: Invoke systemd to start a container
#  stop <name>...                       :: Invoke systemd to stop a container
#  restart <name>...                    :: Invoke systemd to restart a container
#  status <name>...                     :: Retrieve the systemd status of one or more containers
#  list-units <host>...                 :: Retrieve the list of services across all hosts
#  add-keys <id>...                     :: Set keys for SSH access to a resource
#  create-repo <name> [<url>]           :: Create a new git repository
#  daemon                               :: (Local) Start the gear agent
#  clean                                :: (Local) Stop and disable systemd gear units
#  init <name> <image>                  :: (Local) Setup the environment for a container
#  create-token <type> <content_id>     :: (Local) Generate a content request token
#  auth-keys-command <username>         :: (Local) Generate authorized_keys output for sshd.
#  test-router                          :: (Local) Test router extension.
#  init-repo <name> [<url>]             :: (Local) Setup the environment for a git repository
#  help [command]                       :: Help about any command
# Available Flags:
#  -S, --docker-socket="unix:///var/run/docker.sock": Set the docker socket to use
#      --has-env-file=false: (experimental) Use --env-file with Docker, requires master from Apr 1st
#      --has-foreground=false: (experimental) Use --foreground with Docker, requires alexlarsson/forking-run
#      --key-path="": Specify the directory containing the server private key and trusted client public keys
#      --with="": Provide a deployment descriptor to operate on

gear deploy <file.json>
gear status <gearname>
gear list-units
gear start <gearname>
gear stop <gearname>
gear delete <gearname>

# demo gears mongodb-1 & rockmongo-1

gear stop rockmongo-1; gear stop mongodb-1

gear start mongodb-1 ; sleep 60 ; gear start rockmongo-1



