#!/bin/bash NOT A REAL SHELL SCRIPT!
# This is a cut'n'paste scriptlet
# be sure to read & understand what you're cutting & pasting!
#
# ISO date stamp
`date +%Y%m%d-%H%M`


# hostname set in
/etc/hostname

#chkconfig only works with older services, below are on by default
iprdump        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
iprinit        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
iprupdate      	0:off	1:off	2:on	3:on	4:on	5:on	6:off
network        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
rhnsd          	0:off	1:off	2:on	3:on	4:on	5:on	6:off

# this is the new 'chkconfig --list':
systemctl list-unit-files
# by default 75 services are diabled, 53 enabled
# To see services enabled on particular target use
systemctl list-dependencies [target]
# other systemctl commands:
systemctl status tmp.mount
systemctl show tmp.mount
systemctl enable tmp.mount
systemctl start tmp.mount

# on my install I removed the following: 
yum erase "hyperv*"
yum erase "iscsi*"

# rhn_register/rhnreg_ks only for satellite use, for RHN  use:
subscription-manager register

# enabled by default on my install:
abrt-ccpp.service                           enabled 
abrtd.service                               enabled 
abrt-oops.service                           enabled 
abrt-vmcore.service                         enabled 
abrt-xorg.service                           enabled 
atd.service                                 enabled 
auditd.service                              enabled 
avahi-daemon.service                        enabled 
avahi-daemon.socket                         enabled 
chronyd.service                             enabled 
crond.service                               enabled 
dbus-org.fedoraproject.FirewallD1.service   enabled 
dbus-org.freedesktop.Avahi.service          enabled 
dbus-org.freedesktop.NetworkManager.service enabled 
dbus-org.freedesktop.nm-dispatcher.service  enabled 
default.target                              enabled 
dm-event.socket                             enabled 
dmraid-activation.service                   enabled 
firewalld.service                           enabled 
getty@.service                              enabled 
hypervkvpd.service                          enabled 
hypervvssd.service                          enabled 
irqbalance.service                          enabled 
iscsid.socket                               enabled 
iscsi.service                               enabled 
iscsiuio.socket                             enabled 
kdump.service                               enabled 
libstoragemgmt.service                      enabled 
lvm2-lvmetad.socket                         enabled 
lvm2-monitor.service                        enabled 
mdmonitor.service                           enabled 
microcode.service                           enabled 
multipathd.service                          enabled 
multi-user.target                           enabled 
NetworkManager-dispatcher.service           enabled 
NetworkManager.service                      enabled 
nfs-lock.service                            enabled 
nfs.target                                  enabled 
postfix.service                             enabled 
remote-fs.target                            enabled 
rhsmcertd.service                           enabled 
rngd.service                                enabled 
rpcbind.service                             enabled 
rpcbind.socket                              enabled 
rsyslog.service                             enabled 
smartd.service                              enabled 
sshd.service                                enabled 
sysstat.service                             enabled 
systemd-readahead-collect.service           enabled 
systemd-readahead-drop.service              enabled 
systemd-readahead-replay.service            enabled 
tuned.service                               enabled 
vmtoolsd.service                            enabled 

